FROM node:alpine

COPY /src/hello-node.js .

# ENTRYPOINT [ "node", "hello-node.js" ]
CMD ["node", "hello-node.js"]

# What is the difference between CMD and ENTRYPOINT in a Dockerfile? https://stackoverflow.com/q/21553353/1417185
